on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/staging'
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
      - name: "Build only"
        uses: tjtelan/zola-deploy-action@main
        env:
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
          BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
      - name: "Build and deploy"
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
  done:
    name: Done
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: [build_and_deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done!"
